language: r
cache: packages
matrix:
  include:
  - r: oldrel
    os: linux
  - r: release
    os: linux
  - r: devel
    os: linux
  - r: release
    os: osx
before_install:
- set -e
- source <(curl -sSL https://raw.githubusercontent.com/dynverse/travis_scripts/master/helper.sh)
- install_hdf5
- install_dynverse
- install_cran remotes covr
- install_github_withdeps dynverse/dynwrap
after_success:
 - R -e 'covr::codecov()'

